### ISSUE TITLE
Metalness and Roughness files are generating incorrectly.

### ISSUE THREAD

**Issue by poly9-ashish** [soadzoor/Map-Merging-Tool#1]
Hello,

I have 2 files as Metalness and Roughness. When I am trying to use the tool, it give me incorrect output of the file. 

Please help me to resolve this issue. I am giving you both the files.
Roughness File

![finish_ROUGH](https://user-images.githubusercontent.com/53461260/62541899-57322080-b878-11e9-83ab-004f0e0e3033.jpg)

Metalness File

![finish_MTL](https://user-images.githubusercontent.com/53461260/62541900-57322080-b878-11e9-9922-7cede75ec703.jpg)

The output should be Blue color image, but it's getting different color. 

Please help!

**Comment by soadzoor** [comment]
Hey @poly9-ashish ,

With the images you provided, I do get a blue color image, see the screenshot:
![Capture](https://user-images.githubusercontent.com/10392261/62542891-08c35880-b85d-11e9-9209-5fbda856d9b1.PNG)


Is this not what you get?

**Comment by poly9-ashish** [comment]
Hello,
 
Thanks for your quick response. I did mistake to send you the files. Here, I am sending again all the files, so you can review it properly.

I am using the PBR textures in Threejs and Android app. In ThreeJS, I have separate files as Metalness and Roughness. But in Android, when, I am using your Merge Map tool. I am not able to get proper shiny look in Android SceneForm.

Here is the difference. 

![oputput](https://user-images.githubusercontent.com/53461260/62606312-95335100-b919-11e9-9abf-783bf5c9e101.png)


PBR texture files for your reference.

Roughness
![roughness](https://user-images.githubusercontent.com/53461260/62593764-9b173b00-b8f5-11e9-87f7-2367d1bfbbc4.jpg)

Metalness
![metalness](https://user-images.githubusercontent.com/53461260/62593771-a36f7600-b8f5-11e9-9f76-dd15a8f635d3.jpg)

Normal
![normals](https://user-images.githubusercontent.com/53461260/62593812-d31e7e00-b8f5-11e9-9703-b7a47a351903.jpg)

Diffuse
![diffuse](https://user-images.githubusercontent.com/53461260/62593818-d9145f00-b8f5-11e9-820f-97ac52b4fe48.jpg)

Preview Photo of Material
![thumbnail](https://user-images.githubusercontent.com/53461260/62593790-baae6380-b8f5-11e9-812e-5a2e5e512311.png)


Output from online tool
![Screenshot (18)](https://user-images.githubusercontent.com/53461260/62593958-66f04a00-b8f6-11e9-941e-68581642a700.png)

Hope this description will help you to understand my problem.

**Comment by soadzoor** [comment]
My guess is that Android SceneForm doesn't have the same channel-order for this map. Meaning that "usually" R channel represents the occlusion, G channel represents the roughness and B channel represents the Metalness. However, this is not strictly defined, or standardized in the industry, so there's a good chance they use the G channel for metalness and the B channel for roughness, or whatever.

I suggest you ask the SceneForm community about that.

`In ThreeJS, I have separate files as Metalness and Roughness`
-> You can try using the merged map for both metalness map and roughness map, that should save you some loading time, because you'll only have to download one image.

Also, as far as I can see, you basically use single color images..? That's kind of a nonsense, you should just add the specific values to your material without any maps. That's a lot easier and faster.

**Comment by soadzoor** [comment]
Due to inactivity, I'm closing this issue. If you still have questions, please open up a new one.
